#ifndef _ALDEFS_H
#define _ALDEFS_H

#ifndef AL_UNIX
#define AL_UNIX
#endif

#ifndef MEMORY_BLOCK_BYTES
#define MEMORY_BLOCK_BYTES 1024
#endif

enum ALErrors {
  AL_CANT_OPEN_BUFFER = -1200,
  AL_CANT_ALLOCATE_MEMORY,
  AL_CANT_CREATE_ENGINE,
  AL_CANT_CREATE_STORAGE_OBJECT,
  AL_RENAME_ERROR,
  AL_CANT_OPEN_FILE,
  AL_SEEK_ERROR,
  AL_READ_ERROR,
  AL_WRITE_ERROR,
  AL_DELETE_ERROR,
  AL_ILLEGAL_PARAMETER,
  AL_INTERNAL_ERROR,
  AL_USER_ABORT,
  AL_SERVER_NOT_PRESENT,
  AL_COMPRESSION_TYPE_MISMATCH,
  AL_NEED_LENGTH,
  AL_CRC_ERROR,
  AL_COMPARE_ERROR,
  AL_UNKNOWN_COMPRESSION_TYPE,
  AL_UNKNOWN_STORAGE_OBJECT,
  AL_INVALID_ARCHIVE,
  AL_LOGIC_ERROR,
  AL_BACKUP_FAILURE,
  AL_GETSEL_ERROR,
  AL_DUPLICATE_ENTRY,
  AL_END_OF_FILE = -1,
  AL_SUCCESS = 0
};

enum ALGreenleafCompressionLevels {
  AL_GREENLEAF_COPY = -1,
  AL_GREENLEAF_LEVEL_0 = 0,
  AL_GREENLEAF_LEVEL_1,
  AL_GREENLEAF_LEVEL_2,
  AL_GREENLEAF_LEVEL_3,
  AL_GREENLEAF_LEVEL_4,
};

#endif
